# -*- coding: utf-8 -*-
"""TASK 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pq2u7DrvRwaLkuq6Fhp5U9ATo9JuQj_7

Task 2: Case and vowel breakdown
Extend your program so that you also count:
1. uppercase letters and lowercase letters separately,
2. vowels and consonants separately (treat a e i o u as vowels, in either case),
3. how many times each individual vowel appears.
Add these to your report.
"""

Block_of_text = input("Enter the text: ")

UC = 0
LC = 0
V = 0
CS = 0

a_count = 0
e_count = 0
i_count = 0
o_count = 0
u_count = 0

for ch in Block_of_text:
    if ch.isalpha():

        if ch.isupper():
            UC += 1
        elif ch.islower():
            LC += 1

        if ch.lower() in "aeiou":
            V += 1

            if ch.lower() == "a":
                a_count += 1
            elif ch.lower() == "e":
                e_count += 1
            elif ch.lower() == "i":
                i_count += 1
            elif ch.lower() == "o":
                o_count += 1
            elif ch.lower() == "u":
                u_count += 1
        else:
            CS += 1

print("Uppercase letters:", UC)
print("Lowercase letters:", LC)
print("Vowels:", V)
print("a:", a_count)
print("e:", e_count)
print("i:", i_count)
print("o:", o_count)
print("u:", u_count)
print("Consonants:", CS)